export const colors = {
  background: "#FFFFFF",
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surfaceSubtle: "#F3F4F8",
  surfaceSelected: "#EEF2FF",
  surfaceDisabled: "#F3F4F8",
  surfaceInverse: "#0E0E12",
  primary: "#A9BEFF",
  primaryDark: "#3347C2",
  primaryPressed: "#8FA9F5",
  primarySoft: "#EEF2FF",
  primaryTint: "#EEF2FF",
  text: "#0E0E12",
  textSecondary: "#5B5E6B",
  textMuted: "#6B6E7B",
  textDisabled: "#9693A2",
  textTertiary: "#6B6E7B",
  textInverse: "#FFFFFF",
  textLink: "#3347C2",
  border: "#E3E5EC",
  borderStrong: "#CDD1DC",
  borderSubtle: "#F0EEF5",
  borderSelected: "#3347C2",
  borderError: "#B84C59",
  success: "#31805A",
  successSoft: "#EAF6EF",
  warning: "#A86B1D",
  warningSoft: "#FFF4DF",
  error: "#B84C59",
  errorSoft: "#FCEBED",
  info: "#416A9C",
  infoSoft: "#EAF2FA",
  focus: "#3347C2",
  inverse: "#FFFFFF",
  overlay: "rgba(14, 14, 18, 0.04)",
  scrim: "rgba(14, 14, 18, 0.48)",
  ink: "#0E0E12",
  onAccent: "#0E0E12",
} as const;

export const learningColors = {
  notStarted: {
    foreground: colors.textSecondary,
    background: colors.surfaceSubtle,
  },
  inProgress: {
    foreground: colors.primaryDark,
    background: colors.primarySoft,
  },
  completed: { foreground: colors.success, background: colors.successSoft },
  mastered: { foreground: colors.success, background: "#DDF1E5" },
  recommended: {
    foreground: colors.primaryDark,
    background: colors.primaryTint,
  },
  locked: { foreground: colors.textMuted, background: colors.surfaceSubtle },
  current: { foreground: colors.primaryDark, background: colors.primarySoft },
  needsReview: { foreground: colors.warning, background: colors.warningSoft },
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  smPlus: 12,
  md: 16,
  mdPlus: 20,
  lg: 24,
  xl: 32,
  xlPlus: 40,
  xxl: 48,
  xxxl: 64,
} as const;

export const radii = {
  sm: 8,
  md: 14,
  lg: 20,
  xl: 28,
  full: 999,
  circle: 999,
  pill: 999,
  card: 24,
  tile: 16,
} as const;

export const typography = {
  display: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "700" as const,
    letterSpacing: -0.4,
  },
  screenTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700" as const,
    letterSpacing: -0.2,
  },
  sectionHeading: { fontSize: 20, lineHeight: 28, fontWeight: "700" as const },
  sectionTitle: { fontSize: 18, lineHeight: 24, fontWeight: "600" as const },
  cardTitle: { fontSize: 17, lineHeight: 24, fontWeight: "700" as const },
  heading: { fontSize: 24, lineHeight: 32, fontWeight: "700" as const },
  title: { fontSize: 24, lineHeight: 30, fontWeight: "700" as const },
  body: { fontSize: 16, lineHeight: 24, fontWeight: "400" as const },
  bodyMedium: { fontSize: 16, lineHeight: 24, fontWeight: "600" as const },
  bodyStrong: { fontSize: 16, lineHeight: 24, fontWeight: "600" as const },
  bodySmall: { fontSize: 14, lineHeight: 21, fontWeight: "400" as const },
  label: { fontSize: 12, lineHeight: 16, fontWeight: "700" as const },
  caption: { fontSize: 13, lineHeight: 18, fontWeight: "600" as const },
  metadata: { fontSize: 13, lineHeight: 18, fontWeight: "600" as const },
  lessonTitle: { fontSize: 28, lineHeight: 34, fontWeight: "700" as const, letterSpacing: -0.2 },
  lessonHeading: { fontSize: 22, lineHeight: 30, fontWeight: "700" as const },
  lessonSubheading: { fontSize: 17, lineHeight: 24, fontWeight: "600" as const },
  lessonBody: { fontSize: 16, lineHeight: 27, fontWeight: "400" as const },
  lessonCallout: { fontSize: 15, lineHeight: 23, fontWeight: "400" as const },
  codeText: { fontSize: 14, lineHeight: 21, fontWeight: "400" as const },
  button: { fontSize: 15, lineHeight: 20, fontWeight: "700" as const },
  buttonPrimary: { fontSize: 15, lineHeight: 20, fontWeight: "700" as const },
  buttonSecondary: { fontSize: 15, lineHeight: 20, fontWeight: "700" as const },
  textLink: { fontSize: 15, lineHeight: 22, fontWeight: "600" as const },
  numeric: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700" as const,
    fontVariant: ["tabular-nums"] as const,
  },
  navigation: { fontSize: 12, lineHeight: 16, fontWeight: "600" as const },
} as const;

export const elevation = {
  none: {},
  subtle: {
    boxShadow: "0px 1px 4px rgba(33, 31, 43, 0.04)",
    elevation: 1,
  },
  card: {
    boxShadow: "0px 2px 8px rgba(33, 31, 43, 0.06)",
    elevation: 2,
  },
  floating: {
    boxShadow: "0px 6px 16px rgba(33, 31, 43, 0.12)",
    elevation: 6,
  },
} as const;

export const layout = {
  screenPadding: spacing.lg,
  maxContentWidth: 640,
  maxReadingWidth: 680,
  maxChatWidth: 760,
  minimumTouchTarget: 44,
  androidTouchTarget: 48,
  iconButtonSize: 48,
  buttonHeightSmall: 44,
  buttonHeightMedium: 52,
  buttonHeightLarge: 52,
  inputHeight: 52,
  progressHeight: 8,
  iconSmall: 16,
  iconMedium: 20,
  iconLarge: 24,
  iconButton: 22,
  iconNavigation: 24,
  iconHero: 32,
} as const;

export const motion = {
  instant: 0,
  fast: 140,
  normal: 240,
  slow: 380,
  durations: {
    interaction: 140,
    standard: 240,
    emphasized: 380,
  },
  easing: {
    press: "easeOut" as const,
    standard: "easeInOut" as const,
    enter: "easeOut" as const,
    exit: "easeIn" as const,
  },
} as const;

export const welcomeColors = {
  periwinkle: "#A9BEFF",
  periwinklePressed: "#8FA9F5",
  periwinkleHill: "#8FA9F5",
  nearBlack: "#0E0E12",
  brandBlue: "#3347C2",
  inputBg: "#F3F4F8",
  inputBorder: "#E4E5EB",
  mutedGray: "#686575",
  white: "#FFFFFF",
} as const;
